#!/usr/bin/env bash
#/************************************************************************/
#/**
# * @file pod-submit
# * @brief a script, which can be used to manually submit PoD jobs using a defined RMS
# * @author Anar Manafov A.Manafov@gsi.de
# *//*
#
#        created by:        Anar Manafov
#                           2010-11-10
#
#        Copyright (c) 2010-2012 GSI, Scientific Computing division. All rights reserved.
#*************************************************************************/
# 
# The following variables guarantied to be exported by our parent:
# POD_UI_LOG_LOCATION
# POD_UI_LOCATION
#
#
PRIVATE_TOOLS="$POD_LOCATION/bin/private"
#=============================================================================
# ***** MAIN  *****
#=============================================================================
QUEUE="proof"
NUM_WRK=10
while getopts "q:n:h" opt; do
   case $opt in
      q)
       QUEUE="$OPTARG"
       ;;
      n)
       NUM_WRK=$OPTARG
       ;;
      h) 
       usage
       exit 0
       ;;
     \?)
       echo "Invalid option: -$OPTARG" >&2
       exit 1
       ;;
   esac
done

if [ -z "$POD_UI_LOG_LOCATION" ]; then
   echo "Error: PoD UI Log directory is not defined. Please, check you configuration."
fi

EMAIL_JOB_OUTPUT=$(pod-user-defaults --key lsf_plugin.email_job_output)

JOB_NAME="$BASHPID[1-$NUM_WRK]"
OUTPUT=""
if [ $EMAIL_JOB_OUTPUT -eq 0 ]; then
   OUTPUT=" -o $POD_UI_LOG_LOCATION/%J/std_%I.out -e $POD_UI_LOG_LOCATION/%J/std_%I.err"
fi

# add PoD worker script as a payload to the job script
eval WRK_SCRIPT=$(pod-user-defaults --wrkscript)
eval WRK_DIR=$(pod-user-defaults --wn-sandbox-dir)
INPUT_JOB_SCRIPT="$POD_LOCATION/etc/Job.lsf.in"
JOB_SCRIPT="$WRK_DIR/Job.lsf"
WRK_SCRIPT_NAME=$(basename $WRK_SCRIPT)
TMP_WRK_SCRIPT=$WRK_DIR/$WRK_SCRIPT_NAME
pushd $(pwd) &> /dev/null
cp $WRK_SCRIPT $TMP_WRK_SCRIPT
cd $WRK_DIR
tar -czvf $WRK_SCRIPT_NAME.tgz $WRK_SCRIPT_NAME
popd
$PRIVATE_TOOLS/pod-addpayload --binary $TMP_WRK_SCRIPT.tgz $INPUT_JOB_SCRIPT $JOB_SCRIPT
if (( 0 != $? )); then
   echo "error: failed to add payload to the job script."
   exit 1
fi

chmod +x $JOB_SCRIPT

bsub -q $QUEUE -J $JOB_NAME $OUTPUT $JOB_SCRIPT

