#!/usr/bin/env bash
#/************************************************************************/
#/**
# * @file pod-submit
# * @brief a script, which can be used to manually submit PoD jobs using a defined RMS
# * @author Anar Manafov A.Manafov@gsi.de
# *//*
#
#        created by:        Anar Manafov
#                           2010-11-10
#
#        Copyright (c) 2010 GSI, Scientific Computing devision. All rights reserved.
#*************************************************************************/
# 
# The following variables guarantied to be exported by our parent:
# POD_UI_LOG_LOCATION
# POD_UI_LOCATION
#
#
#=============================================================================
# ***** MAIN  *****
#=============================================================================
QUEUE="proof"
NUM_WRK=10
while getopts "q:n:h" opt; do
   case $opt in
      q)
       QUEUE="$OPTARG"
       ;;
      n)
       NUM_WRK=$OPTARG
       ;;
      h) 
       usage
       exit 0
       ;;
     \?)
       echo "Invalid option: -$OPTARG" >&2
       exit 1
       ;;
   esac
done

if [ -z "$POD_UI_LOG_LOCATION" ]; then
   echo "Error: PoD UI Log directory is not defined. Please, check you configuration."
fi

# LOG
eval upload_job_log=$(pod-user-defaults -c $POD_UI_LOCATION/etc/PoD.cfg --key pbs_plugin.upload_job_log)
OUTPUT_LOG=""
if [ "$upload_job_log" = "1" ]; then
   OUTPUT_LOG=" -o $POD_UI_LOG_LOCATION"
else
   OUTPUT_LOG=" -o /dev/null"
fi

# A job array parameter is different in PBS (torque) and PBS pro, it is -t and -J accordingly
# We try to check a version of PBS to figure out, what to use
pbs_pro=$(pbsnodes --version 2>&1 | grep -o PBSPro)
pbs_job_array_param="-J 1-$NUM_WRK"
if [ -z $pbs_pro ]; then
   pbs_job_array_param="-t 1-$NUM_WRK"
fi

jobid=$(qsub -N pod -q $QUEUE $pbs_job_array_param -j oe $OUTPUT_LOG -V -v "POD_UI_LOCATION=$POD_LOCATION, POD_UI_LOG_LOCATION=$POD_UI_LOG_LOCATION" $POD_LOCATION/etc/Job.pbs)
# we need to create a logs output dir
if (( $? == 0 )); then
   echo "Job ID: $jobid"
   if [ "$upload_job_log" = "1" ]; then
      PARENT_PBS_JOBID=$(echo $jobid | egrep -o '^[[:digit:]]*')
      mkdir -p  $POD_UI_LOG_LOCATION/$PARENT_PBS_JOBID
   fi
else
   echo "Error submitting job. $jobid"
fi

